apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-app
  namespace: argocd
spec:
  project: default
  source:
    path: k8s
    repoURL: "https://github.com/Brendon-Hablutzel/hermes-infra"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
