services:
  backend:
    image: ghcr.io/brendon-hablutzel/hermes:latest
    ports:
      - "8080:8080"
    env_file: 
      - .env
    volumes:
      - ./projects.json:/app/projects.json
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  frontend:
    image: ghcr.io/brendon-hablutzel/hermes-ui:latest
    ports:
      - "8000:80"

volumes:
  prometheus_data:
  grafana-storage:

networks:
  monitoring:
