apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: hermes-frontend
          image: ghcr.io/brendon-hablutzel/hermes-ui:linux-arm-v8
          env:
            - name: NEXT_API_URL
              value: "http://backend-service:8080"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
