apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: hermes-backend
          image: ghcr.io/brendon-hablutzel/hermes:linux-arm-v8
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: AWS_REGION
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: CLOUDFLARE_EMAIL
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: CLOUDFLARE_API_KEY
            - name: CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-credentials
                  key: CLOUDFLARE_ACCOUNT_ID
          volumeMounts:
            - name: config-volume
              mountPath: /app/projects.yaml
              subPath: projects.yaml
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: projects-config
