apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hermes
  labels:
    app: backend-service
spec:
  selector:
    app: backend
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
