apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hermes
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030
  type: NodePort
